trigger:
- master
- rel/*

pr:
- master
- rel/*

pool:
  vmImage: windows-2019

variables: 
  BuildConfiguration: Release

steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables
  
- task: NuGetToolInstaller@1
  displayName: Use NuGet 5.7.0
  inputs:
    versionSpec: 5.7.0

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
  inputs:
    forceReinstallCredentialProvider: true

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool

- script: nbgv cloud
  displayName: Set Version

- powershell: |
   Write-Host "##vso[task.setvariable variable=PATH;]${env:LocalAppData}\Microsoft\dotnet;${env:PATH}";
   
   [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; 
   
   dotnet new globaljson --sdk-version "$($env:NET5_SDK_VERSION)" 
   
   &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Version "$($env:NET5_SDK_VERSION)" -Architecture "x64" -AzureFeed "$($env:NET5_SDK_FEED)"
   
  failOnStderr: true
  displayName: 'Install .NET 5 SDK'

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: msbuild
    arguments: /t:restore .\ColorCode.sln
  displayName: NuGet restore

- powershell: .\build\build.ps1
  displayName: Build

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: .\build\nupkg
    artifactType: container
    artifactName: Packages